name: MUtils-NoSameItem
version: '${project.version}'
main: de.maxbossing.mutilsnosameitem.MUtilsNoSameItem
api-version: 1.19
depend: [ Mutils ]
softdepend: [ MUtils ]
authors: [ Max ]
commands:
  resetregisters:
    permission: mutilsnosameitem.resetregisters
permissions:
  mutilsnosameitem.resetregisters:
    default: op